### PR TITLE
Prebuild binaries

### LINKED ISSUE #134: Reducing the file size of the package
**Version** 0.8.4

The MSNodeSqlv8 folder under node_modules is 15MB. 

This is the largest package we have amongst all other installed packages.

About 13MB of this is in the `lib/bin` folder

image

Is there any way to reduce this during the installation? Is there a need for every consumer to have the electron binaries, for instance?

The package size is a problem because it is adding overhead to the time taken to deploy to the cloud.

Thanks for maintaining this repo. It's a great help.

### LINKED ISSUE #143: Electron 8.* Binaries
Electron version 8 was released last month. I've tested building these binaries locally and they appear to compile/run without any additional changes. Can these pre-built binaries be added to `lib\bin\`?

I'm not sure what your philosophy is on pull requests to add binaries. I can submit a pull request with them if you'd accept it.

### PR DESCRIPTION
**Pull request by mtriff**
This change switches from `.bat` files to the `prebuild` module for pre-compiling binaries. prebuild allows binaries to be built for multiple versions of Node and Electron without setting up each version manually on the build machine.

All binaries can now be built using the `npm run prebuild-all` command. Each pre-compiled binary is stored in an individual `.tar.gz` version in the `/prebuilds` folder. These files should be uploaded to each GitHub release in addition to (and separately from) the Source code .zip and .tar.gz.

If a user is using a version of Node/Electron that we have not supplied a pre-compiled binary for, then `npm install` will attempt to run `node-gyp` to compile the binary for their machine.

I've removed the existing binaries from the repo. `.npmignore` has also been updated to remove tests and scripts that are not required for users of this module. This brings the module size from ~14 MB to ~2.25 MB (closes #134).

This change also closes #143.

Since this change may require some users to start compiling the binary, and all Electron users to start using electron-rebuild, I think it is a breaking change and we should version bump to 1.0.0.

---

One issue I haven't been able to resolve is that when a pre-built binary is not available and `node-gyp` is run, the output folder for the build `build\Release` still contains the `obj\` folder, and the `.pdb`, `.lib`, etc files after completing successfully. I don't see this happening with other modules I use. 

This is not a big issue, since most applications will use a pre-built binary or Webpack. But I would appreciate if you have any ideas on what configuration is causing that. 

I still think we should move forward with this change regardless.

### CODE REVIEW

**Comment by TimelordUK** [comment]
OK this looks really good - merged.  So how do we upload the binaries onto a Git release as you mention? i.e. to supply prebuilt.

Thanks a ton for this - a really good step forwards and welcome aboard.

**Comment by TimelordUK** [comment]
this is great!  so right out box I have following binaries

```console
24/03/2020  21:20    <DIR>          .
24/03/2020  21:20    <DIR>          ..
22/03/2020  18:53           356,550 msnodesqlv8-v0.8.13-electron-v76-win32-x64.tar.gz
22/03/2020  19:18           574,344 msnodesqlv8-v0.8.13-node-v72-win32-x64.tar.gz
22/03/2020  19:04           574,352 msnodesqlv8-v0.8.13-node-v79-win32-x64.tar.gz
24/03/2020  21:19           294,565 msnodesqlv8-v1.0.0-electron-v73-win32-ia32.tar.gz
24/03/2020  21:19           361,337 msnodesqlv8-v1.0.0-electron-v73-win32-x64.tar.gz
24/03/2020  21:20           294,578 msnodesqlv8-v1.0.0-electron-v75-win32-ia32.tar.gz
24/03/2020  21:19           361,302 msnodesqlv8-v1.0.0-electron-v75-win32-x64.tar.gz
24/03/2020  21:20           294,569 msnodesqlv8-v1.0.0-electron-v76-win32-ia32.tar.gz
24/03/2020  21:19           361,341 msnodesqlv8-v1.0.0-electron-v76-win32-x64.tar.gz
24/03/2020  21:16           294,299 msnodesqlv8-v1.0.0-node-v64-win32-ia32.tar.gz
24/03/2020  20:59           356,110 msnodesqlv8-v1.0.0-node-v64-win32-x64.tar.gz
24/03/2020  21:16           294,294 msnodesqlv8-v1.0.0-node-v67-win32-ia32.tar.gz
24/03/2020  21:00           356,110 msnodesqlv8-v1.0.0-node-v67-win32-x64.tar.gz
24/03/2020  21:16           458,495 msnodesqlv8-v1.0.0-node-v72-win32-ia32.tar.gz
24/03/2020  21:10           575,548 msnodesqlv8-v1.0.0-node-v72-win32-x64.tar.gz
```
for some reason have an issue with v13 - just looking now

```console
gyp: name 'v8_enable_pointer_compression' is not defined while evaluating condition 'v8_enable_pointer_compression == 1' in binding.gyp while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (C:\AppData\Roaming\nvm\v12.13.1\node_modules\prebuild\node_modules\node-gyp\lib\configure.js:351:16)
prebuild ERR! stack     at ChildProcess.emit (events.js:210:5)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (C:\AppData\Roaming\nvm\v12.13.1\node_modules\prebuild\node_modules\node-gyp\lib\configure.js:351:16)
prebuild ERR! build     at ChildProcess.emit (events.js:210:5)
```

**Comment by TimelordUK** [comment]
sorry my mistake - I was running on node v12, switched to v13 and the whole thing built cleanly.

**Comment by mtriff** [comment]
Happy to be aboard! We'll still create the releases like you normally do (I'm assuming via `npm publish`?). We then upload those individual `.tar.gz` files through either:

1. Manually uploading via the [GitHub web interface](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#editing-a-release)
2. Using the command `npx prebuild upload-all <github-token>` to upload all the .tar.gz files in the `/prebuilds` folder. They will automatically be mapped to the appropriate release. Instructions for creating a GitHub token are [available here](https://github.com/prebuild/prebuild#create-github-token).

After you have uploaded the binaries, the release assets should like similar to [this](https://github.com/atom/node-keytar/releases/tag/v5.4.0).

**Pull request merged**
